---
title: "Portfolio"
format: html
editor: visual
---

## Most recent project

<p>This is my most recent project, completed for the course *Computational Methods: Text Analysis in Python*.
 The goal was to explore how Latin America is represented in UN General Debate speeches using real-world text data, sentiment analysis, and topic modeling techniques.</p>

<table class="table table-hover table-striped table-bordered">
  <thead class="table-light">
    <tr>
      <th>Project</th>
      <th>Goal</th>
      <th>Materials</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Latin America in UN General Debates</td>
      <td>Analyze how Latin America is framed in UN speeches using Python-based text analysis</td>
      <td>
        <a href="project_presentation.html" target="_blank">Presentation</a> |
        <a href="report.html" target="_blank">Report</a>
      </td>
    </tr>
  </tbody>
</table>


## Other projects

<p>Here are a few additional projects I’ve worked on:</p>

<ul>
  <li><a href="presentation.html" target="_blank">No Longer Conforming to Stereotypes? Gender, Political Style and Parliamentary Debate in the UK</a></li>
  <li><a href="projects/PAPER terrorism.docx" target="_blank">How Have the Challenges Posed by Foreign Fighters in ISIS Influenced International Counter-Terrorism Strategies, Laws, and Societal Reintegration Processes?</a></li>
  <li><a href="projects/US protectionism.pdf" target="_blank">US Protectionism: Why Europe Will Suffer More Than China</a></li>
</ul>


